#!/usr/bin/env python3
"""
Sync Location Manifest
----------------------
Scans assets/data/location/*.json and updates assets/data/location/index.json
so all newly added villa JSON files are automatically indexed and detected.
"""

import os
import json
import glob

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
LOC_DIR = os.path.join(BASE_DIR, "assets", "data", "location")

def sync_manifest():
    if not os.path.exists(LOC_DIR):
        print(f"Directory not found: {LOC_DIR}")
        return

    json_files = []
    villas = []
    for fp in glob.glob(os.path.join(LOC_DIR, "*.json")):
        fn = os.path.basename(fp)
        if fn.lower() != "index.json":
            try:
                with open(fp, encoding="utf-8") as source:
                    data = json.load(source)
                if not (isinstance(data, dict)
                        and isinstance(data.get("title") or data.get("name"), str)
                        and any(data.get(key) for key in ("location", "rooms", "spaces", "capacity"))):
                    print(f"Skipping non-villa JSON: {fn}")
                    continue
                json_files.append(fn)
                villas.append({"filename": fn, "data": data})
            except (OSError, ValueError) as error:
                print(f"Skipping {fn}: {error}")

    json_files.sort()
    index_path = os.path.join(LOC_DIR, "index.json")
    with open(index_path, "w") as f:
        json.dump(json_files, f, indent=2)

    fallback_path = os.path.join(BASE_DIR, "assets", "data", "portfolio-fallback.js")
    with open(fallback_path, "w", encoding="utf-8") as f:
        f.write("// Generated by python3 sync_location_manifest.py.\n")
        f.write("window.ADO_PORTFOLIO_FALLBACK = ")
        json.dump(sorted(villas, key=lambda item: item["filename"]), f, ensure_ascii=True)
        f.write(";\n")

    print(f"Updated {index_path} with {len(json_files)} file(s): {json_files}")

if __name__ == "__main__":
    sync_manifest()
